---
headscale_version: "0.22.3" # latest-alpine
headscale_install_dir: "/opt/docker/headscale"

headscale_webui_port: 51821

# https://github.com/headscale/headscale?tab=readme-ov-file#options
headscale_env: {}

headscale_docker_settings: {}
