---
glances_docker_settings_default:
  network: "host"
  puid: "1000"
  pgid: "1000"
  tz: "Etc/UTC"
  healthcheck:
    test: ["CMD", "curl", "--fail", "http://localhost:61208"]
    interval: 5s
    timeout: 5s
    retries: 3

glances_env_default:
  TZ: "{{ glances_docker_settings.tz }}"
  PUID: "{{ glances_docker_settings.puid }}"
  PGID: "{{ glances_docker_settings.pgid }}"
  GLANCES_OPT: "-w"
