paperless_ai_docker_settings_default:
  network: "host"
  puid: "1000"
  pgid: "1000"
  tz: "Etc/UTC"

paperless_ai_env_default:
  TZ: "{{ paperless_ai_docker_settings.tz }}"
  PUID: "{{ paperless_ai_docker_settings.puid }}"
  PGID: "{{ paperless_ai_docker_settings.pgid }}"

  PAPERLESS_API_URL: "http://paperlessngx:8000/api"