---
# https://hub.docker.com/r/vaultwarden/server/tags
vaultwarden_version: "latest-alpine"
vaultwarden_port: 4430
vaultwarden_install_dir: "/opt/docker/vaultwarden"

# https://github.com/dani-garcia/vaultwarden/wiki/Configuration-overview
vaultwarden_env: {}
vaultwarden_docker_settings: {}
