---
namespace: artyorsh

name: selfhosted

version: 1.0.1

readme: README.md

authors:
  - artyorsh

description: An opinionated collection of selfhosted apps, managed with Ansible.

license:
  - MIT

tags:
  - selfhosted
  - docker
  - adguardhome
  - authelia
  - changedetection
  - cloudflare
  - duplicati
  - filebrowser
  - forgejo
  - glances
  - homebox
  - nginx
  - olivetin
  - paperless_ai
  - paperlessngx
  - postiz
  - rss
  - vaultwarden
  - wallos
  - watchtower
  - wgeasy

dependencies:
  "community.docker": ">=3.0.0"

repository: https://github.com/artyorsh/ansible-collection-selfhosted
documentation: https://github.com/artyorsh/ansible-collection-selfhosted
homepage: https://artyorsh.me
issues: https://github.com/artyorsh/ansible-collection-selfhosted/issues

build_ignore: []
