---
- name: "Install and configure wg-easy"
  ansible.builtin.include_tasks: "wgeasy.yml"

- name: "Setup WireGuard client routing via Docker"
  ansible.builtin.include_tasks: "client-routing.yml"
  when: "{{ wgeasy_client_routing_enabled }}"
