---

- name: "Prepare role variables"
  ansible.builtin.set_fact:
    wgeasy_client_ip: "{{ wgeasy_env.WG_DEFAULT_ADDRESS | default('10.8.0.x') | replace('x', '0') }}"

- name: "Get wgeasy container ip address"
  block:
    - name: "Get wgeasy container info"
      community.docker.docker_container_info:
        name: "{{ wgeasy_service_id }}"
      register: wgeasy_container_info

    - name: "Register wg-easy container ip"
      ansible.builtin.set_fact:
        wgeasy_container_ip: "{{ wgeasy_container_info.container.NetworkSettings.Networks[wgeasy_docker_settings.network].IPAddress }}"

- name: "Create systemd route configuration"
  ansible.builtin.copy:
    dest: "/etc/systemd/network/10-global-route.network"
    content: |
      [Route]
      Destination={{ wgeasy_client_ip }}/24
      Gateway={{ wgeasy_container_ip }}

- name: "Restart systemd-networkd service to apply network changes"
  ansible.builtin.systemd:
    name: "systemd-networkd"
    state: "restarted"
    enabled: true
