name: "Run playbook"

inputs:
  tags:
    required: true

runs:
  using: "composite"

  steps:
    - run: |
        ansible-playbook .github/playbook/playbook-github-ci.yml \
        --vault-password-file .github/playbook/vault.ci.sh \
        --tags ${{ inputs.tags }} \
        -v
      shell: "bash"
