---
adguardhome_docker_settings_default:
  network: "host"
  puid: "1000"
  pgid: "1000"
  tz: "Etc/UTC"
  published_ports:
    - "{{ adguardhome_dns_port }}:53/tcp"
    - "{{ adguardhome_dns_port }}:53/udp"
    - "{{ adguardhome_port_http }}:80"
    - "{{ adguardhome_port_https }}:443"
    - "{{ adguardhome_webui_port }}:3000/tcp"

adguardhome_env_default:
  TZ: "{{ adguardhome_docker_settings.tz }}"
  PUID: "{{ adguardhome_docker_settings.puid }}"
  PGID: "{{ adguardhome_docker_settings.pgid }}"
