---
adguardhome_docker_settings_default:
  network: "host"
  puid: "1000"
  pgid: "1000"
  tz: "Etc/UTC"
  healthcheck:
    test: ["CMD", "nslookup", "adguard.com", "127.0.0.1", ">", "/dev/null"]
    start_period: 20s
    interval: 5s
    timeout: 5s
    retries: 3

adguardhome_env_default:
  TZ: "{{ adguardhome_docker_settings.tz }}"
  PUID: "{{ adguardhome_docker_settings.puid }}"
  PGID: "{{ adguardhome_docker_settings.pgid }}"
