---
# https://hub.docker.com/r/paperlessngx/paperless-ngx/tags
paperlessngx_version: "latest"

paperlessngx_port: 9898
paperlessngx_install_dir: "/opt/docker/paperlessngx"
paperlessngx_redis_version: "7.2.4-alpine"

# https://docs.paperless-ngx.com/usage/#the-consumption-directory
paperlessngx_consume_dir: "{{ paperlessngx_install_dir }}/consume"
paperlessngx_media_dir: "{{ paperlessngx_install_dir }}/media"
paperlessngx_export_dir: "{{ paperlessngx_install_dir }}/export"

# https://docs.paperless-ngx.com/configuration/
paperlessngx_env: {}
