---
# https://github.com/wg-easy/wg-easy/pkgs/container/wg-easy
wgeasy_version: "14"
wgeasy_install_dir: "/opt/docker/wg-easy"

wgeasy_client_routing_enabled: false

# https://github.com/wg-easy/wg-easy?tab=readme-ov-file#options
wgeasy_env: {}

wgeasy_docker_settings: {}
