---
duplicati_docker_settings_default:
  network: "host"
  puid: "1000"
  pgid: "1000"
  tz: "Etc/UTC"

duplicati_env_default:
  TZ: "{{ duplicati_docker_settings.tz }}"
  PUID: "{{ duplicati_docker_settings.puid }}"
  PGID: "{{ duplicati_docker_settings.pgid }}"
