---
# https://docs.linuxserver.io/images/docker-filebrowser/#parameters

- name: "Prepare task variables"
  ansible.builtin.set_fact:
    filebrowser_service_id: "filebrowser"
    filebrowser_docker_settings: "{{ filebrowser_docker_settings_default | combine(filebrowser_docker_settings) }}"

- name: "Make sure config directory exists"
  ansible.builtin.file:
    path: "{{ filebrowser_install_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: "directory"
    mode: "0774"

- name: "Make sure {{ filebrowser_docker_settings.network }} docker network exists"
  when: filebrowser_docker_settings.network != "host"
  community.general.docker_network:
    name: "{{ filebrowser_docker_settings.network }}"
    state: "present"

- name: "Create database"
  ansible.builtin.file:
    path: "{{ filebrowser_install_dir }}/filebrowser.db"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: "touch"
    mode: "0774"

- name: "Run filebrowser container"
  community.general.docker_container:
    name: "{{ filebrowser_service_id }}"
    image: "filebrowser/filebrowser:{{ filebrowser_version }}"
    networks:
      - name: "{{ filebrowser_docker_settings.network }}"
    state: "started"
    healthcheck: "{{ filebrowser_docker_settings.healthcheck }}"
    env: "{{ filebrowser_env_default | combine(filebrowser_env) }}"
    ports:
      - "{{ filebrowser_port }}:80"
    volumes:
      - "{{ filebrowser_install_dir }}/filebrowser.db:/database.db"
      - "{{ filebrowser_storage_root_dir }}:/srv"
    restart_policy: "unless-stopped"
