---
- name: "Prepare task variables"
  ansible.builtin.set_fact:
    rssbridge_service_id: "rssbridge"

- name: "Create bridge docker directories"
  ansible.builtin.file:
    path: "{{ freshrss_rssbridge_install_dir }}/config"
    state: "directory"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0664"

- name: "Copy bridge whitelist"
  ansible.builtin.copy:
    src: "files/rssbridge-whitelist.txt"
    dest: "{{ freshrss_rssbridge_install_dir }}/config/whitelist.txt"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0664"

- name: "Run RSSBridge container"
  community.general.docker_container:
    name: "{{ rssbridge_service_id }}"
    image: "rssbridge/rss-bridge:{{ freshrss_rssbridge_version }}"
    networks:
      - name: "{{ freshrss_docker_settings.network }}"
    state: "started"
    ports:
      - "{{ freshrss_rssbridge_port }}:80"
    volumes:
      - "{{ freshrss_rssbridge_install_dir }}/config:/config"
    restart_policy: "unless-stopped"
