---
filebrowser_docker_settings_default:
  network: "host"
  puid: "1000"
  pgid: "1000"
  tz: "Etc/UTC"
  healthcheck:
    test: ["CMD", "curl", "--fail", "http://localhost:80"]
    interval: 5s
    timeout: 5s
    retries: 3

filebrowser_env_default:
  TZ: "{{ filebrowser_docker_settings.tz }}"
  PUID: "{{ filebrowser_docker_settings.puid }}"
  PGID: "{{ filebrowser_docker_settings.pgid }}"
