---
- name: "Prepare task variables"
  ansible.builtin.set_fact:
    vaultwarden_service_id: "vaultwarden"
    vaultwarden_docker_settings: "{{ vaultwarden_docker_settings_default | combine(vaultwarden_docker_settings, recursive=true) }}"

- name: "Make sure config directory exists"
  ansible.builtin.file:
    path: "{{ vaultwarden_install_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: "directory"
    mode: "0774"

- name: "Make sure {{ vaultwarden_docker_settings.network }} docker network exists"
  when: vaultwarden_docker_settings.network != "host"
  community.general.docker_network:
    name: "{{ vaultwarden_docker_settings.network }}"
    state: "present"

- name: "Run vaultwarden container"
  community.general.docker_container:
    name: "{{ vaultwarden_service_id }}"
    image: "vaultwarden/server:{{ vaultwarden_version }}"
    networks:
      - name: "{{ vaultwarden_docker_settings.network }}"
    state: "started"
    healthcheck: "{{ vaultwarden_docker_settings.healthcheck }}"
    env: "{{ vaultwarden_env_default | combine(vaultwarden_env) }}"
    ports:
      - "{{ vaultwarden_port }}:80"
    volumes:
      - "{{ vaultwarden_install_dir }}:/data"
    restart_policy: "unless-stopped"
