---
watchtower_docker_settings_default:
  network: "host"
  puid: "1000"
  pgid: "1000"
  tz: "Etc/UTC"
  healthcheck:
    test: ["CMD", "curl", "--fail", "http://localhost:3080"]
    start_period: 20s
    interval: 5s
    timeout: 5s
    retries: 3

watchtover_env_default:
  TZ: "{{ watchtower_docker_settings.tz }}"
  WATCHTOWER_SCHEDULE: "0 0 2 * * *" # 2AM every day
  WATCHTOWER_REMOVE_VOLUMES: "true"
  WATCHTOWER_NO_STARTUP_MESSAGE: "true"
