---
- name: "Make sure {{ rss_docker_settings.network }} docker network exists"
  when: rss_docker_settings.network != "host"
  community.general.docker_network:
    name: "{{ rss_docker_settings.network }}"
    state: "present"

- name: "Install RSSBridge"
  ansible.builtin.include_tasks: "rssbridge.yml"

- name: "Install Miniflux"
  ansible.builtin.include_tasks: "miniflux.yml"
