# https://hay-kot.github.io/changedetection/quick-start/#env-variables-configuration
---

- name: "Make sure config directories exist"
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: "directory"
    mode: "0750"
  loop:
    - "{{ changedetection_install_dir }}/datastore"

- name: "Run changedetection container"
  community.general.docker_container:
    name: "{{ changedetection_service_id }}"
    image: "dgtlmoon/changedetection.io:{{ changedetection_version }}"
    networks:
      - name: "{{ changedetection_docker_settings.network }}"
    state: "started"
    env: "{{ changedetection_env_default | combine(changedetection_env) }}"
    ports:
      - "{{ changedetection_webui_port }}:5000"
    volumes:
      - "{{ changedetection_install_dir }}/datastore:/datastore"
    restart_policy: "unless-stopped"
