---
- name: "Prepare task variables"
  ansible.builtin.set_fact:
    changedetection_service_id: "changedetection"
    changedection_docker_settings: "{{ changedetection_docker_settings_default | combine(changedetection_docker_settings) }}"

- name: "Make sure {{ changedetection_docker_settings.network }} docker network exists"
  when: changedetection_docker_settings.network != "host"
  community.general.docker_network:
    name: "{{ changedetection_docker_settings.network }}"
    state: "present"

- name: "Install and configure Selenium"
  ansible.builtin.include_tasks: "selenium.yml"

- name: "Install and configure changedetection.io"
  ansible.builtin.include_tasks: "changedetection.yml"
