---
- name: "Run selenium container"
  community.general.docker_container:
    name: "{{ changedetection_service_id }}-selenium"
    image: "seleniarm/standalone-chromium:{{ changedetection_selenium_version }}"
    networks:
      - name: "{{ changedetection_docker_settings.network }}"
    shm_size: "2g"
    state: "started"
    env: "{{ changedetection_selenium_env_default | combine(changedetection_selenium_env) }}"
    ports:
      - "{{ changedetection_selenium_port }}:4444"
    volumes:
      - "{{ changedetection_install_dir }}/datastore:/datastore"
    restart_policy: "unless-stopped"
