---
# https://hub.docker.com/r/linuxserver/freshrss/tags
freshrss_version: "latest"
freshrss_port: 8082
freshrss_install_dir: "/opt/docker/freshrss"

# https://hub.docker.com/r/rssbridge/rss-bridge/tags
freshrss_rssbridge_version: "latest"
freshrss_rssbridge_port: 8083
freshrss_rssbridge_install_dir: "/opt/docker/rssbridge"

freshrss_docker_settings:
  network: "host"
  puid: "1000"
  pgid: "1000"
  tz: "Etc/UTC"