---
roles:
  - name: "geerlingguy.docker"
    src: "https://github.com/geerlingguy/ansible-role-docker"

collections:
  - name: "https://github.com/ansible-collections/community.general"
    type: "git"

  - name: "https://github.com/ansible-collections/ansible.posix"
    type: "git"
