---
# https://hub.docker.com/r/adguard/adguardhome/tags
adguardhome_version: "latest"
adguardhome_install_dir: "/opt/docker/adguardhome"

adguardhome_work_dir: "{{ adguardhome_install_dir }}/work"
adguardhome_config_dir: "{{ adguardhome_install_dir }}/conf"

adguardhome_env: {}

adguardhome_docker_settings: {}
