---
- name: "Github CI playbook"
  hosts: "localhost"
  become: true

  pre_tasks:
    - ansible.builtin.include_role:
        name: "artyorsh.selfhosted.docker"

  vars:
    forgejo_docker_settings:
      puid: "{{ user_uid }}"
      pgid: "{{ user_gid }}"

  roles:
    - role: "artyorsh.selfhosted.duplicati"
      vars:
        duplicati_env:
          SETTINGS_ENCRYPTION_KEY: "supersecret"
      tags: ["duplicati"]

    - role: "artyorsh.selfhosted.forgejo"
      tags: ["forgejo"]
