---
- name: "Run roles"
  hosts: "localhost"
  become: true
  roles:
    - { role: "docker", tags: "docker" }
    - { role: "authelia", tags: "authelia" }
    - { role: "duplicati", tags: "duplicati" }
    - { role: "glances", tags: "glances" }
    - { role: "forjego", tags: "forjego" }
    - { role: "homebox", tags: "homebox" }
    - { role: "miniflux", tags: "miniflux" }
    - { role: "nginx-proxy-manager", tags: "nginx-proxy-manager" }
    - { role: "paperlessngx", tags: "paperlessngx" }
    - { role: "rssbridge", tags: "rssbridge" }
    - { role: "vaultwarden", tags: "vaultwarden" }
    - { role: "wallos", tags: "wallos" }
    - { role: "wgeasy", tags: "wgeasy" }
