---
- name: "Github CI playbook"
  hosts: "localhost"
  become: true

  pre_tasks:
    - ansible.builtin.include_role:
        name: "artyorsh.selfhosted.docker"

  vars:
    forgejo_docker_settings:
      puid: "{{ user_uid }}"
      pgid: "{{ user_gid }}"

  roles:
    - role: "artyorsh.selfhosted.duplicati"
      vars:
        duplicati_env:
          SETTINGS_ENCRYPTION_KEY: "supersecret"
      tags: ["duplicati"]

    - role: "artyorsh.selfhosted.filebrowser"
      tags: ["filebrowser"]

    - role: "artyorsh.selfhosted.forgejo"
      tags: ["forgejo"]

    - role: "artyorsh.selfhosted.glances"
      tags: ["glances"]

    - role: "artyorsh.selfhosted.homarr"
      tags: ["homarr"]

    - role: "artyorsh.selfhosted.nginx"
      vars:
        nginx_docker_settings:
          network: "docker-ci-network"
          puid: "{{ user_uid }}"
          pgid: "{{ user_gid }}"
      tags: ["nginx"]

    - role: "artyorsh.selfhosted.olivetin"
      tags: ["olivetin"]

    - role: "artyorsh.selfhosted.paperless_ai"
      tags: ["paperless_ai"]

    - role: "artyorsh.selfhosted.paperlessngx"
      vars:
        paperlessngx_docker_settings:
          network: "docker-ci-network"
      tags: ["paperlessngx"]

    - role: "artyorsh.selfhosted.rss"
      vars:
        rss_docker_settings:
          network: "docker-ci-network"
      tags: ["rss"]

    - role: "artyorsh.selfhosted.vaultwarden"
      tags: ["vaultwarden"]

    - role: "artyorsh.selfhosted.wallos"
      tags: ["wallos"]