name: "Test (Ubuntu 22.04)"

on:
  pull_request:
    branches:
      - "master"

  push:
    branches:
      - "master"

  workflow_dispatch:

env:
  # SYSTEM_USER: "runner_42" # should match ansible_user (host_vars/github_ci/vars.yml)
  SLEEP_BEFORE_LOADING_APP_URL_SECONDS: 120
  SLEEP_BEFORE_SCREENSHOT_SECONDS: 10

jobs:
  docker:
    runs-on: "ubuntu-22.04"

    strategy:
      matrix:
        role:
          - name: "authelia"
            tags: "docker,authelia"
            screenshot_url: "http://localhost:3019"

          - name: "duplicati"
            tags: "docker,duplicati"
            screenshot_url: "http://localhost:3009"

          - name: "glances"
            tags: "docker,monitoring"
            screenshot_url: "http://localhost:61208"

          - name: "forjego"
            tags: "docker,forjego"
            screenshot_url: "http://localhost:3010"

          - name: "homebox"
            tags: "docker,homebox"
            screenshot_url: "http://localhost:3011"

          - name: "miniflux"
            tags: "docker,rss"
            screenshot_url: "http://localhost:3012"

          - name: "nginx-proxy-manager"
            tags: "docker,nginx"
            screenshot_url: "http://localhost:3018"

          - name: "paperlessngx"
            tags: "docker,media"
            screenshot_url: "http://localhost:3004"

          - name: "rssbridge"
            tags: "docker,rss"
            screenshot_url: "http://localhost:3013"

          - name: "vaultwarden"
            tags: "docker,vaultwarden"
            screenshot_url: "http://localhost:3014"

          - name: "wallos"
            tags: "docker,wallos"
            screenshot_url: "http://localhost:3015"

          - name: "wg-easy"
            tags: "docker,wireguard"
            screenshot_url: "http://localhost:3016"

    steps:
      - uses: "actions/checkout@v4"

      - uses: "./.github/workflows/actions/setup"

      - uses: "./.github/workflows/actions/run-playbook"
        with:
          tags: "${{ matrix.role.tags }}"

      - name: "Sleep before loading app"
        run: "sleep ${{ env.SLEEP_BEFORE_LOADING_APP_URL_SECONDS }}"

      - name: "Print docker processes"
        run: "docker ps -a"

      - name: "Print docker logs"
        run: "docker logs ${{ matrix.role.name }}"

      - name: "Make a screenshot of ${{ matrix.role.screenshot_url }}"
        uses: "karol-brejna-i/webpage-screenshot-action@v1"
        with:
          url: "${{ matrix.role.screenshot_url }}"
          scriptBefore: |
            var waitTill = new Date(new Date().getTime() + ${{ env.SLEEP_BEFORE_SCREENSHOT_SECONDS }} * 1000);
            while(waitTill > new Date()){}
          output: "screenshot-${{ matrix.role.name }}.png"

      - name: "Upload screenshots"
        uses: "actions/upload-artifact@v4"
        with:
          name: "screenshots"
          path: "${{ github.workspace }}/screenshot-*.png"
